### PR TITLE
docs: incorrect reference link

### PR DESCRIPTION
**Pull request by JounQin**
### Initial checklist

* [x] I read the support docs 
* [x] I read the contributing guide 
* [x] I agree to follow the code of conduct 
* [x] I searched issues and couldn’t find anything (or linked relevant results below) 
* [x] If applicable, I’ve added docs and tests

### Description of changes

These links are wrong

### CODE REVIEW

**Comment by JounQin** [comment]
@wooorm 

Besides, it seems a lot of packages are actually not released to npm correctly although the codes are already 7 months old.

**Comment by wooorm** [comment]
Yes, none of the packages are released yet!

**Comment by wooorm** [comment]
I haven’t had time to finish it, as you can see from actions failing as well

**Comment by wooorm** [comment]
Thanks :)

**Comment by JounQin** [comment]
I was surprised https://www.npmjs.com/package/remark-github-break is alive and eventually found out that it is an old/unmaintained package which seems belong to @imcuttle at https://github.com/imcuttle/remark-github-break, can you transfer this package to us?

**Pull request closed without merging**
